const Products = [
  {
    id: 1,
    name: "Apple Watch SE [GPS 40mm], Smartwatch",
    imageLight: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/apple-watch-light.svg",
    imageDark: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/apple-watch-dark.svg",
    discount: 25,
    price: 1199,
    rating: 5,
    reviews: 455,
  },
  {
    id: 2,
    name: "Apple iPhone 15 Pro Max, 256GB, Blue Titanium",
    imageLight: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/iphone-light.svg",
    imageDark: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/iphone-dark.svg",
    discount: 40,
    price: 2500,
    rating: 5,
    reviews: 455,
  },
  {
    id: 3,
    name: "iPad Pro 13-Inch (M4): XDR Display, 512GB",
    imageLight: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/ipad-light.svg",
    imageDark: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/ipad-dark.svg",
    discount: 15,
    price: 1400,
    rating: 5,
    reviews: 455,
  },
  {
    id: 4,
    name: "PlayStation®5 Console – 1TB, PRO Controller",
    imageLight: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/ps5-light.svg",
    imageDark: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/ps5-dark.svg",
    discount: 10,
    price: 2999,
    rating: 5,
    reviews: 455,
  },
  {
    id: 5,
    name: "Microsoft Xbox Series X 1TB Gaming Console",
    imageLight: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/xbox-light.svg",
    imageDark: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/xbox-dark.svg",
    discount: 5,
    price: 3500,
    rating: 5,
    reviews: 455,
  },
  {
    id: 6,
    name: "Apple MacBook PRO Laptop with M2 chip",
    imageLight: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/macbook-pro-light.svg",
    imageDark: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/macbook-pro-dark.svg",
    discount: 20,
    price: 4700,
    rating: 5,
    reviews: 455,
  },
  {
    id: 7,
    name: "Apple iMac 27\"",
    imageLight: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/imac-front.svg",
    imageDark: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/imac-front-dark.svg",
    discount: 35,
    price: 1699,
    rating: 5,
    reviews: 455,
  },
  {
    id: 8,
    name: "Microsoft Surface Pro, Copilot+ PC, 13 Inch",
    imageLight: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/ipad-keyboard.svg",
    imageDark: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/ipad-keyboard-dark.svg",
    discount: 35,
    price: 2499,
    rating: 5,
    reviews: 455,
  },
];

export default Products;